version: 2
jobs:
  build:
    docker:
      - image: welldigital/serverless-build:node8
    steps:
      - checkout
      - restore_cache:
          key: v1-node_modules-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: make install
      - save_cache:
          key: v1-node_modules-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - src/service/node_modules
      - deploy:
          name: Build Assets
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              NODE_ENV=dev make build
            fi
      - deploy:
          name: Update Serverless Dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd src/service
              SLS_DEBUG=* sls deploy --stage dev
              cd ../..
            fi
      - deploy:
          name: Deploy Assets to Dev
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
      